name: Tests

on: push

jobs:
  sbt-test:
    # Name the Job
    name: Run SBT tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SBT Action
        uses: lokkju/github-action-sbt@11-1.3.0-2.12.10